### ISSUE TITLE
Merge import and export mapping apis

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Database-API#119]
Seems doable and fun. It can also be huge from the point of view of maintenance. In addition, we could use a importer spec as exporter spec and vice versa, which also seems huge.

**Comment by manuelma** [comment]
Done, but we need to update some tests. I will do it next.

**Comment by jkiviluo** [comment]
Sounds great. However, I was testing and got a problem. It is probably an issue with time series data that I was trying to import (that pesky TradeRES project).

At first, importer did not import time series, but imported other things (I didn't check for traceback at that point). I was also able to open the import specification in Toolbox. However, after probably saving the spec, it did not open in Toolbox any longer. It is giving this traceback now:

``` 
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\importer.py", line 197, in _handle_files_double_clicked
    self.open_import_editor(index)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\importer.py", line 213, in open_import_editor
    self._toolbox.show_specification_form(self.item_type(), self.specification(), self, filepath=filepath)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 1643, in show_specification_form
    self.item_factories[item_type].show_specification_widget(self, specification, item, **kwargs)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\importer_factory.py", line 65, in show_specification_widget
    _import_editor_manager.create_editor(toolbox, specification, item, filepath)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\widgets.py", line 370, in create_editor
    editor = self._editors[key] = self._constructor(toolbox, specification, item, *args, **kwargs)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\widgets\import_editor_window.py", line 126, in __init__
    self.start_ui(filepath)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\widgets\import_editor_window.py", line 205, in start_ui
    self._editor = ImportEditor(self, mapping)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\widgets\import_editor.py", line 63, in __init__
    self._restore_mapping(mapping)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\widgets\import_editor.py", line 250, in _restore_mapping
    for table, mapping_specifications in mapping.get("table_mappings", {}).items()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\widgets\import_editor.py", line 250, in <dictcomp>
    for table, mapping_specifications in mapping.get("table_mappings", {}).items()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\widgets\import_editor.py", line 246, in <listcomp>
    [MappingSpecificationModel.from_dict(m, table, self._undo_stack) for m in mapping_specifications],
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\mvcmodels\mapping_specification_model.py", line 863, in from_dict
    name, mapping = parse_named_mapping_spec(named_mapping_spec)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\import_mapping_compat.py", line 68, in parse_named_mapping_spec
    return name, import_mapping_from_dict(mapping)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\import_mapping_compat.py", line 79, in import_mapping_from_dict
    return mapping_from_dict(map_dict)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\import_mapping.py", line 978, in from_dict
    flattened.append(mappings[mapping_dict["map_type"]].reconstruct(position, mapping_dict))
KeyError: 'ParameterValueType'
```

**Comment by manuelma** [comment]
Sorry about that. The original spec must have been saved with a `json.bak` extension next to the new one, can you share that file?

**Comment by jkiviluo** [comment]
No worries, I'm glad I can spot problems. Next time, maybe we should do user testing on a branch?

[base.json.bak.txt](https://github.com/Spine-project/Spine-Database-API/files/6139601/base.json.bak.txt)

**Comment by manuelma** [comment]
> Next time, maybe we should do user testing on a branch?

That's actually a pretty good idea. Thanks for the file, will investigate.
