### ISSUE TITLE
Imporing pivoted data with empty pivot fails

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Database-API#155]
Pivoted import mappings will give the following Traceback if the pivot part of the table is empty:

```
[10.30] Kiviluoma Juha
Traceback (most recent call last):
[snip]
File "spine-items\spine_items\importer\do_work.py", line 65, in do_work
data, errors = connector.get_mapped_data(
File "spinedb-api\spinedb_api\spine_io\importers\reader.py", line 132, in get_mapped_data
data, t_errors = get_mapped_data(
File "spinedb-api\spinedb_api\import_mapping\generator.py", line 85, in get_mapped_data
unpivoted_rows, pivoted_pos, non_pivoted_pos, unpivoted_column_pos = _unpivot_rows(
File "spinedb-api\spinedb_api\import_mapping\generator.py", line 211, in _unpivot_rows
unpivoted_column_pos = [k for k in range(len(rows[0])) if k not in skip_pos]
IndexError: list index out of range
```

Reported by @jkiviluo

**Comment by soininen** [comment]
Fixed.
