### ISSUE TITLE
Traceback when calling cascade_remove_items() when database has entity groups

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Database-API#162]
`DatabaseMapping.cascade_remove_items()` may raise an unexpected exception when there are entity groups in the database:

```
Error
Traceback (most recent call last):
[...]
  File "spinedb_api\db_mapping_remove_mixin.py", line 34, in cascade_remove_items
    cascading_ids = self.cascading_ids(cache=cache, **kwargs)
  File "spinedb_api\db_mapping_remove_mixin.py", line 69, in cascading_ids
    self._merge(ids, self._object_class_cascading_ids(kwargs.get("object_class", set()), cache))
  File "spinedb_api\db_mapping_remove_mixin.py", line 120, in _object_class_cascading_ids
    self._merge(cascading_ids, self._object_cascading_ids({x.id for x in objects}, cache))
  File "spinedb_api\db_mapping_remove_mixin.py", line 136, in _object_cascading_ids
    groups = [x for x in cache.get("entity_group", {}).values() if {x.entity_id, x.member_id}.intersection(ids)]
  File "spinedb_api\db_mapping_remove_mixin.py", line 136, in <listcomp>
    groups = [x for x in cache.get("entity_group", {}).values() if {x.entity_id, x.member_id}.intersection(ids)]
AttributeError: 'result' object has no attribute 'entity_id'
```

The error seems to stem from a small oversight: `ext_entity_group_sq` used by the cache object labels `entity_id` as `group_id` so changing `entity_id` to `group_id` on last code line mentioned in the Traceback should fix the problem.

**Comment by soininen** [comment]
Fixed.
