### ISSUE TITLE
Traceback when importing pivoted data with short rows

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Database-API#169]
I have a small pivoted test table in a .csv file:
```
 , T1, T2
 param, 5, 3
 
```

Note that the last line is not empty but contains an accidental space. Trying to import the data results in a Traceback:

```
Process ReturningProcess-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "spine_engine\utils\returning_process.py", line 47, in run
    result = self._target(*self._args, **self._kwargs)
  File spine_items\importer\do_work.py", line 62, in do_work
    data, errors = connector.get_mapped_data(
  File "spinedb_api\spine_io\importers\reader.py", line 132, in get_mapped_data
    data, t_errors = get_mapped_data(
  File "spinedb_api\import_mapping\generator.py", line 126, in get_mapped_data
    full_row.append(row[column_pos])
IndexError: list index out of range
```

The Traceback hangs Toolbox execution. I think we should rather print a warning.

**Comment by soininen** [comment]
Fixed.
