### ISSUE TITLE
DB manager broken

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Database-API#179]
I'm afraid commit https://github.com/Spine-project/Spine-Database-API/commit/1b09311a019e764135b905d6ee1878205673568c breaks DB manager. On Toolbox startup, I get this:

```
(spi38) C:\data\SpineToolbox>python spinetoolbox.py
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\data\SpineToolbox\src\spinedb-api\spinedb_api\spine_db_server.py", line 87, in _do_work
    result = handler(*args, **kwargs)
  File "C:\data\SpineToolbox\src\spinedb-api\spinedb_api\spine_db_server.py", line 484, in _do_start_server
    _db_manager.open_db_map(server.server_address, db_url, upgrade, memory)
NameError: name '_db_manager' is not defined

```

Workflows don't execute - they got stuck in the first item.

**Comment by manuelma** [comment]
Sorry about that. Let me check. Are you sure you get that traceback at toolbox stratup and not after you pressed play?

**Comment by jkiviluo** [comment]
It was probably after first play, but I didn't realize, since it didn't repeat on next play. I'll test your fix.

**Comment by jkiviluo** [comment]
Now I got this when trying to run a merger:`

```
(spi38) C:\data\SpineToolbox>python spinetoolbox.py
Process ReturningProcess-3:
Traceback (most recent call last):
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\data\SpineToolbox\src\spine-engine\spine_engine\utils\returning_process.py", line 52, in run
    return_value = self._target(self, *self._args, **self._kwargs)
  File "C:\data\SpineToolbox\src\spine-items\spine_items\merger\do_work.py", line 32, in do_work
    to_client.open_connection()
AttributeError: 'SpineDBClient' object has no attribute 'open_connection'
```

**Comment by manuelma** [comment]
Seems to work better after a couple of commits to spine-db-api and spine-items.

**Comment by jkiviluo** [comment]
ok, I hadn't pulled spine-items

**Comment by jkiviluo** [comment]
seems to roll after I did `bin\upgrade...`
