### ISSUE TITLE
Parallel importing leads to multiple next_ids

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Database-API#180]
Running Toolbox execution tests leads to the following Traceback:

```
Traceback (most recent call last):
  File "lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "spinedb_api\spine_db_server.py", line 222, in _do_work
    result = handler(*args, **kwargs)
  File "spinedb_api\spine_db_server.py", line 240, in _do_import_data
    count, errors = import_data(self._db_map, unparse_value=_unparse_value, **data)
  File "spinedb_api\import_functions.py", line 158, in import_data
    for tablename, (to_add, to_update, errors) in get_data_for_import(
  File "spinedb_api\import_functions.py", line 287, in get_data_for_import
    _get_object_parameter_values_for_import(
  File "spinedb_api\import_functions.py", line 1384, in _get_object_parameter_values_for_import
    alt_id, alternative_name = db_map.get_import_alternative(cache=cache)
  File "spinedb_api\db_mapping_base.py", line 1768, in get_import_alternative
    self._create_import_alternative(cache=cache)
  File "spinedb_api\filters\execution_filter.py", line 161, in _create_import_alternative
    alt_ids, _ = db_map.add_alternatives({"name": db_map._import_alternative_name}, return_dups=True)
  File "spinedb_api\db_mapping_add_mixin.py", line 311, in add_alternatives
    return self.add_items("alternative", *items, **kwargs)
  File "spinedb_api\db_mapping_add_mixin.py", line 151, in add_items
    ids = self._add_items(tablename, *checked_items)
  File "spinedb_api\db_mapping_add_mixin.py", line 170, in _add_items
    self._add_commit_id_and_ids(tablename, *items)
  File "spinedb_api\db_mapping_add_mixin.py", line 89, in _add_commit_id_and_ids
    next_id_row = self.query(self._next_id).one_or_none()
  File "lib\site-packages\sqlalchemy\orm\query.py", line 3467, in one_or_none
    raise orm_exc.MultipleResultsFound(
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()
```

Looks like we create too many next_ids.

**Comment by manuelma** [comment]
Should work better after above commit - thanks so much for the steps to reproduce @soininen and sorry everybody for the troubles.

The cuplrit was a change from one my latest commits. Basically, Importer and Merger were locking the DB file very soon, before any changes were actually made to the DB. I removed this to increase concurrency and it indeed increased to the point where two parallel threads would eventually have the possibility to start writing to the DB at almost the same time -leading to the above TB.

But we also weren't locking the DB properly at the begining of each write operation, where we collect ids for the new items. We thought that begining a transaction would do the trick, as I read somewhere in SQLite documentation or so I believe, but that wasn't the case.

So now we lock the DB by inserting the record to the commit table a bit earlier.
