### ISSUE TITLE
Something in spine_db_server.py breaks Toolbox unit tests

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Database-API#185]
Looks like commit 255787a in spinedb_api breaks running a subset of unit tests on Spine Toolbox side. Happens on Windows, both Python 3.8 and 3.9. If I run all the tests `python -m unittest --verbose` it works (!) but running for example just the tests in `<toolbox_repo>/tests/test_helpers.py`, bad things happen. Downgrading spinedb_api to commit 1ec95ab or older makes the tests run perfect again.

```
C:\data\GIT\SPINETOOLBOX>python -m unittest tests\test_helpers.py --verbose
test_replaces_br_by_newline (test_helpers.TestHTMLTagFilter) ... ok
test_simple_log_line (test_helpers.TestHTMLTagFilter) ... ok
test_copy_files (test_helpers.TestHelpers) ... ok
test_copy_files_with_excludes (test_helpers.TestHelpers) ... ok
test_copy_files_with_includes (test_helpers.TestHelpers) ... ok
test_create_dir (test_helpers.TestHelpers) ... ok
test_dir_is_valid (test_helpers.TestHelpers) ... ok
test_erase_dir (test_helpers.TestHelpers) ... ok
test_file_is_valid (test_helpers.TestHelpers) ... ok
test_first_non_null (test_helpers.TestHelpers) ... ok
test_format_log_message (test_helpers.TestHelpers) ... ok
test_format_string_list (test_helpers.TestHelpers) ... ok
test_get_datetime (test_helpers.TestHelpers) ... ok
test_interpret_icon_id (test_helpers.TestHelpers) ... ok
test_load_local_project_data (test_helpers.TestHelpers) ... ok
test_load_project_dict (test_helpers.TestHelpers) ... ok
test_load_tool_specification_from_file (test_helpers.TestHelpers)
Tests creating a PythonTool (specification) instance from a valid tool specification file. ... ok
test_make_icon_id (test_helpers.TestHelpers) ... ok
test_merge_dicts (test_helpers.TestHelpers) ... ok
test_merge_dicts_when_source_contains_nested_dict_not_present_in_target (test_helpers.TestHelpers) ... ok
test_merge_dicts_when_source_overwrites_data_in_target (test_helpers.TestHelpers) ... ok
test_merge_dicts_with_empty_source (test_helpers.TestHelpers) ... ok
test_recursive_overwrite (test_helpers.TestHelpers) ... ok
test_rename_dir (test_helpers.TestHelpers) ... ok
test_rename_dir_prompts_user_if_target_exists (test_helpers.TestHelpers) ... ok
test_row_to_row_count_tuples (test_helpers.TestHelpers) ... ok
test_select_julia_executable (test_helpers.TestHelpers) ... ok
test_select_julia_project (test_helpers.TestHelpers) ... ok
test_select_python_interpreter (test_helpers.TestHelpers) ... ok
test_try_number_from_string (test_helpers.TestHelpers) ... ok
test_tuple_itemgetter (test_helpers.TestHelpers) ... ok
test_unique_name (test_helpers.TestHelpers) ... ok

----------------------------------------------------------------------
Ran 32 tests in 0.429s

OK
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python39\lib\multiprocessing\connection.py", line 707, in PipeClient
    _winapi.WaitNamedPipe(address, 1000)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python39\lib\multiprocessing\connection.py", line 707, in PipeClient
    _winapi.WaitNamedPipe(address, 1000)
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

Then after giving it Ctrl-c

```
Process Process-2:
Process Process-1:
Traceback (most recent call last):
  File "C:\Python39\lib\multiprocessing\connection.py", line 683, in accept
    res = _winapi.WaitForMultipleObjects(
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "C:\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python39\lib\multiprocessing\connection.py", line 683, in accept
    res = _winapi.WaitForMultipleObjects(
  File "C:\data\GIT\SPINETOOLBOX\src\spinedb-api\spinedb_api\spine_db_server.py", line 99, in _do_work
    with listener.accept() as conn:
KeyboardInterrupt
  File "C:\Python39\lib\multiprocessing\connection.py", line 468, in accept
    c = self._listener.accept()

During handling of the above exception, another exception occurred:

  File "C:\Python39\lib\multiprocessing\connection.py", line 691, in accept
    assert err == 0
Traceback (most recent call last):
AssertionError
  File "C:\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\data\GIT\SPINETOOLBOX\src\spinedb-api\spinedb_api\spine_db_server.py", line 99, in _do_work
    with listener.accept() as conn:
  File "C:\Python39\lib\multiprocessing\connection.py", line 468, in accept
    c = self._listener.accept()
  File "C:\Python39\lib\multiprocessing\connection.py", line 691, in accept
    assert err == 0
AssertionError
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python39\lib\multiprocessing\util.py", line 357, in _exit_function
    p.join()
  File "C:\Python39\lib\multiprocessing\process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "C:\Python39\lib\multiprocessing\popen_spawn_win32.py", line 108, in wait
    res = _winapi.WaitForSingleObject(int(self._handle), msecs)
KeyboardInterrupt
```

**Comment by PekkaSavolainen** [comment]
Fixed by #187. Thanks @manuelma.
